### ISSUE TITLE
Missing upload photo button in contact editor dropdown

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#90]
In the previous version of the contact editor, there was an upload photo button in the `photo` data set of the `other information field`.

Now, when you add a `Photo` or `Logo` type field in the `Other Information` section, there is only an option to delete the photo/logo.

There is a dropdown next to the delete button that doesn't do anything:

**Steps to reproduce:**

1. Try to edit an existing contact
2. Add a photo in the `Other Information` section
3. Click on the dropdown next to the delete button
4. Notice nothing expands from the dropdown and there is no way to add a photo or logo

**Video:**

![2019-08-08_19-04-06](https://user-images.githubusercontent.com/44697797/62723158-4c11f880-ba10-11e9-9063-9d8d46311165.gif)

**Comment by vincaslt** [comment]
This got fixed in https://github.com/ProtonMail/react-components/pull/168
It must have been a broken dropdown, and it's working for me from what I've tested.

@emnproton could you retest this now please?

**Comment by emnproton** [comment]
@vincaslt still doesn't work for me, but perhaps the PR is not currently on the live deploy.

Will re-test on the next deploy.
